description = "Tests secret detection regexes with a trial suite."
prompt = """
**SECRET DETECTION TESTING**

Creating a temporary test file for secret detection...

!{
TEMP_FILE="$(mktemp)"
cat > "$TEMP_FILE" << EOF
# Test file for secret detection

My API_KEY is sk-test-1234567890abcdefghijklmnopqrstuvwxyz
This is a regular string with no secrets.
Another secret: password=my_super_secret_password
Not a secret: my_variable = "some_value"

# AWS credentials
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

# False positive example
This is a test of a long string that might look like a key but isn't: 1234567890abcdef1234567890abcdef1234567890abcdef
EOF

chmod 600 "$TEMP_FILE"

echo "Temporary test file created at: $TEMP_FILE"

# Invoke the security_scan tool
gemini -p "/security:scan file_path=$TEMP_FILE scan_type=secrets"

# Clean up the temporary file (optional, for manual review)
# rm "$TEMP_FILE"
}

Review the output above for detected secrets and false positives. Adjust regex patterns in settings.json if necessary.
"""
